// <auto-generated />
using System;
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20251030154426_UpdateCouponAndDiscountTier")]
    partial class UpdateCouponAndDiscountTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ApplicableCategories")
                        .HasColumnType("TEXT");

                    b.Property<int>("CampaignType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouponCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTiered")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxStackPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumPurchaseAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentageDiscount")
                        .HasColumnType("REAL");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.0,
                            CampaignType = 0,
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentUsageCount = 0,
                            Description = "IPhone X New",
                            IsAutomatic = false,
                            IsStackable = true,
                            IsTiered = false,
                            MaxStackPercentage = 30.0,
                            MaxUsageCount = 0,
                            MinimumPurchaseAmount = 0.0,
                            PercentageDiscount = 0.0,
                            Priority = 0,
                            ProductId = "",
                            ProductName = "IPhone X",
                            Scope = 0,
                            Status = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            CampaignType = 0,
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentUsageCount = 0,
                            Description = "Samsung 10 New",
                            IsAutomatic = false,
                            IsStackable = true,
                            IsTiered = false,
                            MaxStackPercentage = 30.0,
                            MaxUsageCount = 0,
                            MinimumPurchaseAmount = 0.0,
                            PercentageDiscount = 0.0,
                            Priority = 0,
                            ProductId = "",
                            ProductName = "Samsung 10",
                            Scope = 0,
                            Status = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Discount.Grpc.Models.DiscountTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FixedDiscount")
                        .HasColumnType("REAL");

                    b.Property<double>("MinAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PercentageDiscount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.ToTable("DiscountTier", (string)null);
                });

            modelBuilder.Entity("Discount.Grpc.Models.DiscountTier", b =>
                {
                    b.HasOne("Discount.Grpc.Models.Coupon", null)
                        .WithMany("Tiers")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
