// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PercentageDiscount")
                        .HasColumnType("REAL");

                    b.Property<string>("CouponCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxStackPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.0,
                            Description = "IPhone X New",
                            ProductName = "IPhone X",
                            ProductId = "",
                            Type = 0,
                            PercentageDiscount = 0.0,
                            IsStackable = true,
                            MaxStackPercentage = 30.0,
                            Priority = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            Description = "Samsung 10 New",
                            ProductName = "Samsung 10",
                            ProductId = "",
                            Type = 0,
                            PercentageDiscount = 0.0,
                            IsStackable = true,
                            MaxStackPercentage = 30.0,
                            Priority = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
